version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80

  # The Database
  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=rmutsb"
      - "MYSQL_USER=rmutsb"
      - "MYSQL_PASSWORD=aton"
      - "MYSQL_ROOT_PASSWORD=aton"
    ports:
        - "3306:3306"

  # The phpMyAdmin
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    restart: always
    ports:
        - '8181:80'
    links:
        - database:mysql
    environment:
        MYSQL_USERNAME: rmutsb
        MYSQL_ROOT_PASSWORD: aton
        PMA_HOST: mysql

volumes:
  dbdata:
